version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    entrypoint:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hotel_costacode_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=dair@777
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dair@777
      MYSQL_DATABASE: hotel_costacode_db
      MYSQL_USER: root
      MYSQL_PASSWORD: dair@777

    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:



